Fix TLS bug preventing HTTPS-over-HTTP(S) proxying
delvedor/hpagent pull request #51
Opened 2022-02-19 03:00 UTC by freeqaz

Without this fix, you see this error when attempting to use an HTTPS proxy.

`Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: foo.com. is not in the cert's altnames: DNS:*.bar.com, DNS:bar.com`

The `servername` attribute is able to fix this behavior when passed to the underlying `tls.connect()` call inside of the `https` module. (see the Node [docs](https://nodejs.org/api/https.html#httpsrequesturl-options-callback))

This was very painful to debug but now I understand how `CONNECT` works extremely well! Cheers.

FIxes #43

2022-03-17 09:39 UTC, ckcr4lyf commented
This is essential as otherwise the requests hostname is attempted to be matched with the proxy's cert.

+1 from me thanks

2022-03-21 07:28 UTC, delvedor requested changes
Thanks for the fix! Can you add a unit test?

2022-03-22 05:36 UTC, ckcr4lyf commented
If they don't do it, do you think it's possible for me to checkout their branch into another, add a unit test, and make another MR?

While still having @freeqaz as an author / contributor? (I can't commit to their branch obviously)

2022-03-24 08:55 UTC, delvedor commented
@ckcr4lyf yes, it should be possible.

2022-04-27 12:12 UTC, arnaudruffin commented
I had the same issue and I can confirm that this fix works perfectly ! Thanks @freeqaz. While waiting for this PR to be merged il will just copy/paste your code with the right mentions...

2022-05-02 05:02 UTC, ckcr4lyf commented
I am working on the unittest for this. Just to explain a bit more on Free's fix, I setup the unit test with two domains, one for the server (HTTP target) - `server.unit-test.com` , one for the proxy - `proxy-domain.net` . 

When I comment out Free's fix, the SSL-over-SSL test sends the SNI for `server.unit-test.com` in TLS handshake with proxy:
![image](https://user-images.githubusercontent.com/6680615/166186368-90670b30-7e8f-4fc6-b478-96414e75c209.png)

But with the fix, it will correctly use the  proxy's hostname in the SNI header for the initial handshake with the proxy:
![image](https://user-images.githubusercontent.com/6680615/166186490-3666cf7b-8407-4bf1-88ef-dcca35a14006.png)

adding the unit test is a bit complicated, hopefully you guys wont mind reviewing it :smile:

2022-05-02 06:59 UTC, ckcr4lyf commented
@delvedor I have added unit tests (and changed quite a bit...) in a new MR, building on Free's work -> https://github.com/delvedor/hpagent/pull/65

2022-05-02 15:40 UTC, delvedor commented
Closed by https://github.com/delvedor/hpagent/pull/65.

2022-05-02 15:40 UTC, closed without merging