Add support for proxyRequestOptions
delvedor/hpagent pull request #72
Opened 2022-05-22 17:08 UTC by mbargiel

This PR adds a new property to the constructor `options`, `proxyRequestOptions`, which allows callers to provide options for  the 
 CONNECT request made against the proxy. There are various reasons to do this:
- A custom `ca` may need to be passed to the proxy connection but not the upstream connection (or vice versa) and the `ca` value is not known at launch or can change over time, preventing the use of `NODE_EXTRA_CA_CERTS` as a viable alternative because that environment variable is only used by Node during startup
- Specific proxy headers may need to be sent which differ from the upstream request; for instance, `Proxy-Authentication` should be sent only to the proxy and `Authorization` should only be sent to the upstream server.

Implements #69 
Note: this PR introduces a merge conflict with #71. Whichever lands first will require a manual merge before the other can land.

2022-09-18 15:01 UTC, mbargiel commented
Hi @delvedor ! I see you reviewed #81 which is practically the same as this PR (with subtle differences, and this one has tests) but not this one. Is there anything missing to this one?

2022-09-27 14:39 UTC, delvedor requested changes
~Great work! Can you update the `requestOption` object to allow adding other custom options, such as the one described in https://github.com/delvedor/hpagent/issues/69?~

Edit: I've missed a line in the review, the changes are good.
Can you update the types and the README as well?

Thanks!

2022-09-27 15:19 UTC, mbargiel commented
@delvedor Will do! Expect an update within a day or two.

2022-09-28 13:47 UTC, mbargiel commented
@delvedor See https://github.com/delvedor/hpagent/pull/72/commits/5f4f3fef68789b038b5a34f2ad7f874baa1d28d7. Please note that I used a single type for both agent types because the proxy options and upstream protocol are orthogonal: you may need to pass https (TLS) connect options to a proxy agent of either types HttpProxyAgent or HttpsProxyAgent, since either can be used over an HTTPS proxy connection.

2022-10-07 09:57 UTC, delvedor approved these changes
LGTM

2022-10-07 10:01 UTC, merged

2022-10-07 10:09 UTC, delvedor commented
Released in `v1.1.0`, thanks for contributing!